packages:
  - .
  - packages/*

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - msw

patchedDependencies:
  next-themes@0.4.6: patches/next-themes@0.4.6.patch

trustPolicy: warn
