import type { IconType } from "react-icons";
import {
  SiAfterpay,
  SiAirbnb,
  SiAirtable,
  SiApplemusic,
  SiApplepay,
  SiAsana,
  SiBehance,
  SiBookingdotcom,
  SiBox,
  SiCalendly,
  SiCanva,
  SiCashapp,
  SiClickup,
  SiDeliveroo,
  SiDiscord,
  SiDoordash,
  SiDribbble,
  SiDropbox,
  SiEbay,
  SiEtsy,
  SiExpedia,
  SiFacebook,
  SiFigma,
  SiGithub,
  SiGitlab,
  SiGmail,
  SiGooglecalendar,
  SiGoogledrive,
  SiGooglemaps,
  SiGooglemeet,
  SiGooglepay,
  SiGrab,
  SiGumroad,
  SiInstagram,
  SiKlarna,
  SiLine,
  SiLinktree,
  SiLyft,
  SiMailchimp,
  SiMedium,
  SiMessenger,
  SiNetflix,
  SiNotion,
  SiPatreon,
  SiPaypal,
  SiPinterest,
  SiProtonmail,
  SiRazorpay,
  SiReddit,
  SiRevolut,
  SiShopify,
  SiSignal,
  SiSlack,
  SiSnapchat,
  SiSoundcloud,
  SiSpotify,
  SiSquare,
  SiSquarespace,
  SiStripe,
  SiSubstack,
  SiSwiggy,
  SiTelegram,
  SiThreads,
  SiTiktok,
  SiTrello,
  SiTripadvisor,
  SiTumblr,
  SiTwitch,
  SiUber,
  SiVenmo,
  SiViber,
  SiVimeo,
  SiWaze,
  SiWebflow,
  SiWechat,
  SiWetransfer,
  SiWhatsapp,
  SiWise,
  SiWix,
  SiWoocommerce,
  SiWordpress,
  SiX,
  SiYelp,
  SiYoutube,
  SiYoutubemusic,
  SiZomato,
  SiZoom,
} from "react-icons/si";

export type BrandIconCategory = "business" | "media" | "payments" | "social" | "travel" | "web";

export type BrandIconEntry = {
  category: BrandIconCategory;
  icon: IconType;
  id: string;
  label: string;
};

export const BRAND_ICON_CATALOG = [
  {
    id: "instagram",
    label: "Instagram",
    category: "social",
    icon: SiInstagram,
  },
  {
    id: "whatsapp",
    label: "WhatsApp",
    category: "social",
    icon: SiWhatsapp,
  },
  {
    id: "facebook",
    label: "Facebook",
    category: "social",
    icon: SiFacebook,
  },
  {
    id: "messenger",
    label: "Messenger",
    category: "social",
    icon: SiMessenger,
  },
  {
    id: "threads",
    label: "Threads",
    category: "social",
    icon: SiThreads,
  },
  {
    id: "x",
    label: "X",
    category: "social",
    icon: SiX,
  },
  {
    id: "tiktok",
    label: "TikTok",
    category: "social",
    icon: SiTiktok,
  },
  {
    id: "youtube",
    label: "YouTube",
    category: "social",
    icon: SiYoutube,
  },
  {
    id: "telegram",
    label: "Telegram",
    category: "social",
    icon: SiTelegram,
  },
  {
    id: "snapchat",
    label: "Snapchat",
    category: "social",
    icon: SiSnapchat,
  },
  {
    id: "pinterest",
    label: "Pinterest",
    category: "social",
    icon: SiPinterest,
  },
  {
    id: "discord",
    label: "Discord",
    category: "social",
    icon: SiDiscord,
  },
  {
    id: "reddit",
    label: "Reddit",
    category: "social",
    icon: SiReddit,
  },
  {
    id: "tumblr",
    label: "Tumblr",
    category: "social",
    icon: SiTumblr,
  },
  {
    id: "twitch",
    label: "Twitch",
    category: "social",
    icon: SiTwitch,
  },
  {
    id: "patreon",
    label: "Patreon",
    category: "social",
    icon: SiPatreon,
  },
  {
    id: "substack",
    label: "Substack",
    category: "social",
    icon: SiSubstack,
  },
  {
    id: "medium",
    label: "Medium",
    category: "social",
    icon: SiMedium,
  },
  {
    id: "behance",
    label: "Behance",
    category: "social",
    icon: SiBehance,
  },
  {
    id: "dribbble",
    label: "Dribbble",
    category: "social",
    icon: SiDribbble,
  },
  {
    id: "wechat",
    label: "WeChat",
    category: "social",
    icon: SiWechat,
  },
  {
    id: "line",
    label: "Line",
    category: "social",
    icon: SiLine,
  },
  {
    id: "signal",
    label: "Signal",
    category: "social",
    icon: SiSignal,
  },
  {
    id: "viber",
    label: "Viber",
    category: "social",
    icon: SiViber,
  },
  {
    id: "notion",
    label: "Notion",
    category: "business",
    icon: SiNotion,
  },
  {
    id: "airtable",
    label: "Airtable",
    category: "business",
    icon: SiAirtable,
  },
  {
    id: "trello",
    label: "Trello",
    category: "business",
    icon: SiTrello,
  },
  {
    id: "asana",
    label: "Asana",
    category: "business",
    icon: SiAsana,
  },
  {
    id: "clickup",
    label: "ClickUp",
    category: "business",
    icon: SiClickup,
  },
  {
    id: "calendly",
    label: "Calendly",
    category: "business",
    icon: SiCalendly,
  },
  {
    id: "zoom",
    label: "Zoom",
    category: "business",
    icon: SiZoom,
  },
  {
    id: "google-meet",
    label: "Google Meet",
    category: "business",
    icon: SiGooglemeet,
  },
  {
    id: "slack",
    label: "Slack",
    category: "business",
    icon: SiSlack,
  },
  {
    id: "dropbox",
    label: "Dropbox",
    category: "business",
    icon: SiDropbox,
  },
  {
    id: "google-drive",
    label: "Google Drive",
    category: "business",
    icon: SiGoogledrive,
  },
  {
    id: "box",
    label: "Box",
    category: "business",
    icon: SiBox,
  },
  {
    id: "wetransfer",
    label: "WeTransfer",
    category: "business",
    icon: SiWetransfer,
  },
  {
    id: "canva",
    label: "Canva",
    category: "business",
    icon: SiCanva,
  },
  {
    id: "figma",
    label: "Figma",
    category: "business",
    icon: SiFigma,
  },
  {
    id: "paypal",
    label: "PayPal",
    category: "payments",
    icon: SiPaypal,
  },
  {
    id: "stripe",
    label: "Stripe",
    category: "payments",
    icon: SiStripe,
  },
  {
    id: "razorpay",
    label: "Razorpay",
    category: "payments",
    icon: SiRazorpay,
  },
  {
    id: "square",
    label: "Square",
    category: "payments",
    icon: SiSquare,
  },
  {
    id: "venmo",
    label: "Venmo",
    category: "payments",
    icon: SiVenmo,
  },
  {
    id: "cash-app",
    label: "Cash App",
    category: "payments",
    icon: SiCashapp,
  },
  {
    id: "revolut",
    label: "Revolut",
    category: "payments",
    icon: SiRevolut,
  },
  {
    id: "wise",
    label: "Wise",
    category: "payments",
    icon: SiWise,
  },
  {
    id: "apple-pay",
    label: "Apple Pay",
    category: "payments",
    icon: SiApplepay,
  },
  {
    id: "google-pay",
    label: "Google Pay",
    category: "payments",
    icon: SiGooglepay,
  },
  {
    id: "shopify",
    label: "Shopify",
    category: "payments",
    icon: SiShopify,
  },
  {
    id: "woocommerce",
    label: "WooCommerce",
    category: "payments",
    icon: SiWoocommerce,
  },
  {
    id: "etsy",
    label: "Etsy",
    category: "payments",
    icon: SiEtsy,
  },
  {
    id: "ebay",
    label: "eBay",
    category: "payments",
    icon: SiEbay,
  },
  {
    id: "gumroad",
    label: "Gumroad",
    category: "payments",
    icon: SiGumroad,
  },
  {
    id: "klarna",
    label: "Klarna",
    category: "payments",
    icon: SiKlarna,
  },
  {
    id: "afterpay",
    label: "Afterpay",
    category: "payments",
    icon: SiAfterpay,
  },
  {
    id: "google-maps",
    label: "Google Maps",
    category: "travel",
    icon: SiGooglemaps,
  },
  {
    id: "waze",
    label: "Waze",
    category: "travel",
    icon: SiWaze,
  },
  {
    id: "yelp",
    label: "Yelp",
    category: "travel",
    icon: SiYelp,
  },
  {
    id: "tripadvisor",
    label: "Tripadvisor",
    category: "travel",
    icon: SiTripadvisor,
  },
  {
    id: "booking-com",
    label: "Booking.com",
    category: "travel",
    icon: SiBookingdotcom,
  },
  {
    id: "airbnb",
    label: "Airbnb",
    category: "travel",
    icon: SiAirbnb,
  },
  {
    id: "uber",
    label: "Uber",
    category: "travel",
    icon: SiUber,
  },
  {
    id: "lyft",
    label: "Lyft",
    category: "travel",
    icon: SiLyft,
  },
  {
    id: "doordash",
    label: "DoorDash",
    category: "travel",
    icon: SiDoordash,
  },
  {
    id: "swiggy",
    label: "Swiggy",
    category: "travel",
    icon: SiSwiggy,
  },
  {
    id: "zomato",
    label: "Zomato",
    category: "travel",
    icon: SiZomato,
  },
  {
    id: "grab",
    label: "Grab",
    category: "travel",
    icon: SiGrab,
  },
  {
    id: "deliveroo",
    label: "Deliveroo",
    category: "travel",
    icon: SiDeliveroo,
  },
  {
    id: "expedia",
    label: "Expedia",
    category: "travel",
    icon: SiExpedia,
  },
  {
    id: "spotify",
    label: "Spotify",
    category: "media",
    icon: SiSpotify,
  },
  {
    id: "apple-music",
    label: "Apple Music",
    category: "media",
    icon: SiApplemusic,
  },
  {
    id: "soundcloud",
    label: "SoundCloud",
    category: "media",
    icon: SiSoundcloud,
  },
  {
    id: "netflix",
    label: "Netflix",
    category: "media",
    icon: SiNetflix,
  },
  {
    id: "vimeo",
    label: "Vimeo",
    category: "media",
    icon: SiVimeo,
  },
  {
    id: "youtube-music",
    label: "YouTube Music",
    category: "media",
    icon: SiYoutubemusic,
  },
  {
    id: "github",
    label: "GitHub",
    category: "web",
    icon: SiGithub,
  },
  {
    id: "gitlab",
    label: "GitLab",
    category: "web",
    icon: SiGitlab,
  },
  {
    id: "wordpress",
    label: "WordPress",
    category: "web",
    icon: SiWordpress,
  },
  {
    id: "webflow",
    label: "Webflow",
    category: "web",
    icon: SiWebflow,
  },
  {
    id: "wix",
    label: "Wix",
    category: "web",
    icon: SiWix,
  },
  {
    id: "squarespace",
    label: "Squarespace",
    category: "web",
    icon: SiSquarespace,
  },
  {
    id: "linktree",
    label: "Linktree",
    category: "web",
    icon: SiLinktree,
  },
  {
    id: "gmail",
    label: "Gmail",
    category: "web",
    icon: SiGmail,
  },
  {
    id: "proton-mail",
    label: "Proton Mail",
    category: "web",
    icon: SiProtonmail,
  },
  {
    id: "google-calendar",
    label: "Google Calendar",
    category: "web",
    icon: SiGooglecalendar,
  },
  {
    id: "mailchimp",
    label: "Mailchimp",
    category: "web",
    icon: SiMailchimp,
  },
] as const satisfies readonly BrandIconEntry[];

export type BrandIconId = (typeof BRAND_ICON_CATALOG)[number]["id"];

export const POPULAR_BRAND_ICON_IDS = [
  "whatsapp",
  "instagram",
  "facebook",
  "youtube",
  "tiktok",
  "telegram",
  "spotify",
  "paypal",
  "google-maps",
  "shopify",
  "github",
] as const satisfies readonly BrandIconId[];

const BRAND_ICON_BY_ID = new Map<string, BrandIconEntry>(
  BRAND_ICON_CATALOG.map((entry) => [entry.id, entry]),
);

export function findBrandIconById(id?: string) {
  if (!id) {
    return undefined;
  }

  return BRAND_ICON_BY_ID.get(id);
}

export function getBrandIconById(id: BrandIconId) {
  const brandIcon = findBrandIconById(id);

  if (!brandIcon) {
    throw new Error(`Unknown brand icon: ${id}`);
  }

  return brandIcon;
}
