import {
  DitheringTypes,
  GemSmokeShapes,
  GlassDistortionShapes,
  GlassGridShapes,
  HalftoneCmykTypes,
  HalftoneDotsGrids,
  HalftoneDotsTypes,
  LiquidMetalShapes,
  gemSmokeMeta,
  heatmapMeta,
} from "@paper-design/shaders";
import {
  color,
  controls,
  IMAGE_SHADER_HIDDEN_PARAMS,
  number,
  option,
  SHADER_FIT_OPTIONS,
  toggle,
  withColors,
  withImageControls,
  type PaperShaderControlConfig,
} from "@/features/canvas/rendering/paper-shaders/shared";

export const IMAGE_FILTER_SHADER_CONTROL_CONFIG: Record<string, PaperShaderControlConfig> = {
  "fluted-glass": {
    controls: withImageControls([
      color("colorBack", 100),
      color("colorShadow", 101),
      color("colorHighlight", 102),
      number("shadows", 0, 1, 200),
      number("highlights", 0, 1, 201),
      number("size", 0.01, 1, 210, 0.01),
      option("shape", Object.keys(GlassGridShapes), 211),
      number("angle", 0, 180, 212),
      option("distortionShape", Object.keys(GlassDistortionShapes), 213),
      number("distortion", 0, 1, 214),
      number("shift", -1, 1, 215),
      number("stretch", 0, 1, 216),
      number("blur", 0, 1, 220),
      number("edges", 0, 1, 221),
      number("margin", 0, 0.5, 500),
      number("grainMixer", 0, 1, 550),
      number("grainOverlay", 0, 1, 551),
      number("scale", 0.5, 4, 600),
      option("fit", SHADER_FIT_OPTIONS, 604),
    ]),
    hiddenParams: [
      ...IMAGE_SHADER_HIDDEN_PARAMS,
      "rotation",
      "offsetX",
      "offsetY",
      "marginLeft",
      "marginRight",
      "marginTop",
      "marginBottom",
    ],
    requiresImage: true,
  },
  "image-dithering": {
    controls: withImageControls([
      color("colorBack", 100),
      color("colorFront", 102),
      color("colorHighlight", 103),
      toggle("originalColors", 104),
      toggle("inverted", 105),
      option("type", Object.keys(DitheringTypes), 200),
      number("size", 1, 20, 201),
      number("colorSteps", 1, 7, 202, 1),
      number("scale", 0.5, 4, 300),
      option("fit", SHADER_FIT_OPTIONS, 301),
    ]),
    hiddenParams: [...IMAGE_SHADER_HIDDEN_PARAMS, "rotation", "offsetX", "offsetY"],
    requiresImage: true,
  },
  heatmap: {
    hiddenParams: IMAGE_SHADER_HIDDEN_PARAMS,
    requiresImage: true,
    ...withColors(heatmapMeta.maxColorCount, [
      { key: "image", order: 0, type: "image" },
      color("colorBack", 102),
      number("contour", 0, 1, 103),
      number("angle", 0, 360, 104, 1),
      number("noise", 0, 1, 105),
      number("innerGlow", 0, 1, 106),
      number("outerGlow", 0, 1, 107),
      number("speed", 0, 2, 300),
      number("scale", 0.01, 4, 301),
      number("rotation", 0, 360, 302, 1),
      number("offsetX", -1, 1, 303),
      number("offsetY", -1, 1, 304),
    ]),
  },
  "liquid-metal": {
    controls: withImageControls([
      color("colorBack", 100),
      color("colorTint", 101),
      option("shape", Object.keys(LiquidMetalShapes), 102),
      number("repetition", 1, 10, 200),
      number("softness", 0, 1, 201),
      number("shiftRed", -1, 1, 202),
      number("shiftBlue", -1, 1, 203),
      number("distortion", 0, 1, 204),
      number("contour", 0, 1, 205),
      number("angle", 0, 360, 206, 1),
      number("speed", 0, 4, 300),
      number("scale", 0.2, 4, 301),
      number("rotation", 0, 360, 302, 1),
      number("offsetX", -1, 1, 303),
      number("offsetY", -1, 1, 304),
      option("fit", SHADER_FIT_OPTIONS, 305),
    ]),
    hiddenParams: IMAGE_SHADER_HIDDEN_PARAMS,
    requiresImage: true,
  },
  "halftone-dots": {
    controls: withImageControls([
      color("colorBack", 100),
      color("colorFront", 101),
      toggle("originalColors", 102),
      option("type", Object.keys(HalftoneDotsTypes), 201),
      option("grid", Object.keys(HalftoneDotsGrids), 202),
      toggle("inverted", 203),
      number("size", 0.01, 1, 300, 0.001),
      number("radius", 0, 2, 301),
      number("contrast", 0.01, 1, 302),
      number("grainMixer", 0, 1, 350),
      number("grainOverlay", 0, 1, 351),
      number("grainSize", 0, 1, 352),
      number("scale", 0.1, 4, 400),
      number("offsetX", -1, 1, 401),
      number("offsetY", -1, 1, 402),
      number("rotation", 0, 360, 420, 1),
      option("fit", SHADER_FIT_OPTIONS, 450),
    ]),
    hiddenParams: IMAGE_SHADER_HIDDEN_PARAMS,
    requiresImage: true,
  },
  "halftone-cmyk": {
    controls: withImageControls([
      color("colorBack", 100),
      color("colorC", 101),
      color("colorM", 102),
      color("colorY", 103),
      color("colorK", 104),
      number("size", 0.01, 1, 120, 0.01),
      number("gridNoise", 0, 1, 121, 0.01),
      option("type", Object.keys(HalftoneCmykTypes), 123),
      number("softness", 0, 1, 124, 0.01),
      number("contrast", 0, 2, 130, 0.01),
      number("gainC", -1, 1, 200, 0.01),
      number("gainM", -1, 1, 201, 0.01),
      number("gainY", -1, 1, 202, 0.01),
      number("gainK", -1, 1, 203, 0.01),
      number("floodC", 0, 1, 210, 0.01),
      number("floodM", 0, 1, 211, 0.01),
      number("floodY", 0, 1, 212, 0.01),
      number("floodK", 0, 1, 213, 0.01),
      number("grainMixer", 0, 1, 350),
      number("grainOverlay", 0, 1, 351),
      number("grainSize", 0, 1, 352),
      number("offsetX", -1, 1, 401),
      number("offsetY", -1, 1, 402),
      number("rotation", 0, 360, 420, 1),
      number("scale", 0, 4, 420),
      option("fit", SHADER_FIT_OPTIONS, 450),
    ]),
    hiddenParams: IMAGE_SHADER_HIDDEN_PARAMS,
    requiresImage: true,
  },
  "gem-smoke": {
    hiddenParams: IMAGE_SHADER_HIDDEN_PARAMS,
    requiresImage: true,
    ...withColors(gemSmokeMeta.maxColorCount, [
      { key: "image", order: 0, type: "image" },
      color("colorBack", 100),
      color("colorInner", 101),
      option("shape", Object.keys(GemSmokeShapes), 102),
      number("innerDistortion", 0, 1, 201),
      number("outerDistortion", 0, 1, 202),
      number("outerGlow", 0, 1, 203),
      number("innerGlow", 0, 1, 204),
      number("offset", -1, 1, 205),
      number("angle", 0, 360, 250, 1),
      number("size", 0.1, 1, 251),
      number("speed", 0, 4, 300),
      number("scale", 0.1, 4, 301),
      number("rotation", 0, 360, 302, 1),
      number("offsetX", -1, 1, 303),
      number("offsetY", -1, 1, 304),
      option("fit", SHADER_FIT_OPTIONS, 305),
    ]),
  },
};
