import {
  DitheringShapes,
  DitheringTypes,
  DotGridShapes,
} from "@paper-design/shaders"
import {
  color,
  COMMON_HIDDEN_PARAMS,
  controls,
  HIGH_RES_SHADER_MAX_PIXEL_COUNT,
  number,
  option,
  SHADER_FIT_OPTIONS,
  withColors,
  type PaperShaderControlConfig,
} from "@/features/canvas/rendering/paper-shaders/shared"

export const TEXTURE_SHADER_CONTROL_CONFIG: Record<string, PaperShaderControlConfig> = {
  waves: {
    controls: controls(
      color("colorBack", 100),
      color("colorFront", 101),
      number("frequency", 0, 2, 300),
      number("amplitude", 0, 1, 301),
      number("spacing", 0, 2, 302),
      number("proportion", 0, 1, 303),
      number("softness", 0, 1, 304),
      number("shape", 0, 3, 350),
      number("scale", 0.01, 4, 400),
      number("rotation", 0, 360, 401, 1),
    ),
    hiddenParams: COMMON_HIDDEN_PARAMS,
    renderOptions: { maxPixelCount: HIGH_RES_SHADER_MAX_PIXEL_COUNT },
  },
  "dot-orbit": {
    hiddenParams: COMMON_HIDDEN_PARAMS,
    ...withColors(10, [
      color("colorBack", 100),
      number("stepsPerColor", 1, 4, 200, 1),
      number("size", 0, 1, 201),
      number("sizeRange", 0, 1, 202),
      number("spreading", 0, 1, 203),
      number("speed", 0, 20, 300),
      number("scale", 0.01, 5, 301),
    ]),
  },
  "dot-grid": {
    controls: controls(
      color("colorBack", 100),
      color("colorFill", 101),
      color("colorStroke", 102),
      option("shape", Object.keys(DotGridShapes), 199),
      number("size", 1, 100, 200),
      number("gapX", 2, 500, 201),
      number("gapY", 2, 500, 202),
      number("strokeWidth", 0, 50, 203),
      number("sizeRange", 0, 1, 204),
      number("opacityRange", 0, 1, 205),
      number("rotation", 0, 360, 303, 1),
    ),
    hiddenParams: COMMON_HIDDEN_PARAMS,
    renderOptions: { maxPixelCount: HIGH_RES_SHADER_MAX_PIXEL_COUNT },
  },
  "perlin-noise": {
    controls: controls(
      color("colorBack", 100),
      color("colorFront", 101),
      number("proportion", 0, 1, 200),
      number("softness", 0, 1, 201),
      number("octaveCount", 1, 8, 202, 1),
      number("persistence", 0.3, 1, 203),
      number("lacunarity", 1.5, 10, 204),
      number("speed", 0, 0.5, 300),
      number("scale", 0.01, 4, 301),
      number("rotation", 0, 360, 302, 1),
    ),
    hiddenParams: COMMON_HIDDEN_PARAMS,
  },
  spiral: {
    controls: controls(
      color("colorBack", 100),
      color("colorFront", 101),
      number("density", 0, 1, 200),
      number("distortion", 0, 1, 201),
      number("strokeWidth", 0, 1, 202),
      number("strokeTaper", 0, 1, 203),
      number("strokeCap", 0, 1, 204),
      number("noise", 0, 1, 205),
      number("noiseFrequency", 0, 1, 206),
      number("softness", 0, 1, 207),
      number("speed", 0, 2, 300),
      number("scale", 0.01, 4, 301),
      number("rotation", 0, 360, 302, 1),
      number("offsetX", -1, 1, 303),
      number("offsetY", -1, 1, 304),
    ),
    hiddenParams: COMMON_HIDDEN_PARAMS,
  },
  dithering: {
    controls: controls(
      color("colorBack", 100),
      color("colorFront", 101),
      option("shape", Object.keys(DitheringShapes), 200),
      option("type", Object.keys(DitheringTypes), 201),
      number("size", 1, 20, 202),
      number("speed", 0, 2, 300),
      number("scale", 0.01, 4, 301),
      number("rotation", 0, 360, 302, 1),
      number("offsetX", -1, 1, 303),
      number("offsetY", -1, 1, 304),
    ),
    hiddenParams: COMMON_HIDDEN_PARAMS,
  },
  "paper-texture": {
    controls: controls(
      color("colorBack", 100),
      color("colorFront", 101),
      number("contrast", 0, 1, 200),
      number("roughness", 0, 1, 201),
      number("fiber", 0, 1, 202),
      number("fiberSize", 0.01, 1, 203),
      number("crumples", 0, 1, 204),
      number("crumpleSize", 0.01, 1, 205),
      number("folds", 0, 1, 206),
      number("foldCount", 1, 15, 207, 1),
      number("fade", 0, 1, 208),
      number("drops", 0, 1, 209),
      number("seed", 0, 1000, 250, 1),
      number("scale", 0.5, 4, 300),
      option("fit", SHADER_FIT_OPTIONS, 301),
    ),
    hiddenParams: ["frame", "speed", "rotation", "offsetX", "offsetY", "originX", "originY", "worldWidth", "worldHeight"],
  },
  water: {
    controls: controls(
      color("colorBack", 100),
      color("colorHighlight", 101),
      number("highlights", 0, 1, 200),
      number("layering", 0, 1, 201),
      number("edges", 0, 1, 202),
      number("waves", 0, 1, 203),
      number("caustic", 0, 1, 204),
      number("size", 0.01, 5, 205),
      number("speed", 0, 3, 300),
      number("scale", 0.1, 4, 301),
      option("fit", SHADER_FIT_OPTIONS, 302),
    ),
    hiddenParams: ["frame", "speed", "rotation", "offsetX", "offsetY", "originX", "originY", "worldWidth", "worldHeight"],
  },
}

