import {
  isAcuityAppointmentPath,
  isAcuitySchedulePath,
  isBookingComHotelPath,
  isBookingComSharePath,
  isCalComEventPath,
  isCalComPrivatePath,
  isCalComTeamPath,
  isCalComUserPath,
  isCalendlyCollectivePath,
  isCalendlyEventPath,
  isCalendlyOneOffPath,
  isCalendlyProfilePath,
  isGoogleFormsFullPath,
  isGoogleFormsHost,
  isGoogleFormsShortHost,
  isJotformFormHost,
  isJotformSubmitPath,
  isMicrosoftFormsPagePath,
  isMicrosoftFormsShortPath,
  isRazorpayInvoicePath,
  isRazorpayShortLinkPath,
  isSquarePayPath,
  isTallyFormPath,
  isTypeformPath,
  isVenmoPaymentPath,
  isVenmoProfilePath,
} from "@/features/qr/content/platform-path-matching";
import type { PlatformDef } from "@/features/qr/content/intents/shared";

export const BUSINESS_PLATFORM_DEFS: readonly PlatformDef[] = [
  {
    type: "google-review",
    label: "Google Review",
    category: "business",
    hosts: ["g.page", "business.google.com", "maps.google.com"],
    intents: [{ id: "place", label: "Place" }],
  },
  {
    type: "calendly",
    label: "Calendly",
    category: "business",
    hosts: ["calendly.com"],
    brandIconId: "calendly",
    intents: [
      { id: "one-off", label: "One-off", matchPath: (p) => isCalendlyOneOffPath(p) },
      { id: "collective", label: "Collective", matchPath: (p) => isCalendlyCollectivePath(p) },
      { id: "event", label: "Event", matchPath: (p) => isCalendlyEventPath(p) },
      { id: "profile", label: "Profile", matchPath: (p) => isCalendlyProfilePath(p) },
    ],
  },
  {
    type: "cal-com",
    label: "Cal.com",
    category: "business",
    hosts: ["cal.com"],
    brandIconId: "calendly",
    intents: [
      { id: "private", label: "Private link", matchPath: (p) => isCalComPrivatePath(p) },
      { id: "team", label: "Team event", matchPath: (p) => isCalComTeamPath(p) },
      { id: "event", label: "Event", matchPath: (p) => isCalComEventPath(p) },
      { id: "user", label: "User", matchPath: (p) => isCalComUserPath(p) },
    ],
  },
  {
    type: "booking-com",
    label: "Booking.com",
    category: "business",
    hosts: ["booking.com"],
    brandIconId: "booking-com",
    intents: [
      { id: "share", label: "Share", matchPath: (p) => isBookingComSharePath(p) },
      { id: "hotel", label: "Hotel", matchPath: (p) => isBookingComHotelPath(p) },
    ],
  },
  {
    type: "acuity",
    label: "Acuity",
    category: "business",
    hosts: ["acuityscheduling.com", "as.me"],
    brandIconId: "calendly",
    intents: [
      {
        id: "appointment",
        label: "Appointment",
        matchPath: (p, params) => isAcuityAppointmentPath(p, params),
      },
      {
        id: "schedule",
        label: "Schedule",
        matchPath: (p, _params, hostname) => isAcuitySchedulePath(p, hostname ?? ""),
      },
    ],
  },
  {
    type: "stripe",
    label: "Stripe",
    category: "business",
    hosts: ["buy.stripe.com", "book.stripe.com", "donate.stripe.com", "checkout.stripe.com"],
    brandIconId: "stripe",
    intents: [
      {
        id: "checkout",
        label: "Checkout",
        matchPath: (_p, _params, hostname) => hostname === "checkout.stripe.com",
      },
      {
        id: "donate",
        label: "Donate",
        matchPath: (_p, _params, hostname) => hostname === "donate.stripe.com",
      },
      {
        id: "book",
        label: "Book",
        matchPath: (_p, _params, hostname) => hostname === "book.stripe.com",
      },
      {
        id: "pay",
        label: "Pay",
        matchPath: (_p, _params, hostname) => hostname === "buy.stripe.com",
      },
    ],
  },
  {
    type: "razorpay",
    label: "Razorpay",
    category: "business",
    hosts: ["rzp.io", "razorpay.com"],
    brandIconId: "razorpay",
    intents: [
      {
        id: "invoice",
        label: "Invoice",
        matchPath: (p, _params, hostname) => isRazorpayInvoicePath(p, hostname ?? ""),
      },
      {
        id: "link",
        label: "Payment link",
        matchPath: (p, _params, hostname) => isRazorpayShortLinkPath(p, hostname ?? ""),
      },
    ],
  },
  {
    type: "square",
    label: "Square",
    category: "business",
    hosts: ["square.link", "squareup.com"],
    brandIconId: "square",
    intents: [
      {
        id: "pay",
        label: "Pay",
        matchPath: (p, _params, hostname) => isSquarePayPath(p, hostname ?? ""),
      },
      {
        id: "checkout",
        label: "Checkout",
        matchPath: (_p, _params, hostname) => hostname === "square.link",
      },
    ],
  },
  {
    type: "paypal-me",
    label: "PayPal.me",
    category: "business",
    hosts: ["paypal.me"],
    intents: [{ id: "profile", label: "Profile" }],
  },
  {
    type: "venmo",
    label: "Venmo",
    category: "business",
    hosts: ["venmo.com"],
    intents: [
      { id: "payment", label: "Payment", matchPath: (p, params) => isVenmoPaymentPath(p, params) },
      { id: "profile", label: "Profile", matchPath: (p, params) => isVenmoProfilePath(p, params) },
    ],
  },
  {
    type: "cash-app",
    label: "Cash App",
    category: "business",
    hosts: ["cash.app"],
    intents: [{ id: "cashtag", label: "Cashtag", matchPath: (p) => p.includes("/$") }],
  },
  {
    type: "google-forms",
    label: "Google Forms",
    category: "business",
    hosts: ["forms.gle", "docs.google.com"],
    brandIconId: "google",
    matchHost: (hostname, pathname) => isGoogleFormsHost(hostname, pathname),
    intents: [
      {
        id: "short",
        label: "Short link",
        matchPath: (_p, _params, hostname) => isGoogleFormsShortHost(hostname ?? ""),
      },
      { id: "form", label: "Form", matchPath: (p) => isGoogleFormsFullPath(p) },
    ],
  },
  {
    type: "microsoft-forms",
    label: "Microsoft Forms",
    category: "business",
    hosts: ["forms.office.com", "forms.microsoft.com"],
    brandIconId: "microsoft",
    intents: [
      { id: "page", label: "Response page", matchPath: (p) => isMicrosoftFormsPagePath(p) },
      { id: "form", label: "Form", matchPath: (p) => isMicrosoftFormsShortPath(p) },
    ],
  },
  {
    type: "typeform",
    label: "Typeform",
    category: "business",
    hosts: ["typeform.com", "form.typeform.com"],
    intents: [{ id: "form", label: "Form", matchPath: (p) => isTypeformPath(p) }],
  },
  {
    type: "tally",
    label: "Tally",
    category: "business",
    hosts: ["tally.so"],
    intents: [{ id: "form", label: "Form", matchPath: (p) => isTallyFormPath(p) }],
  },
  {
    type: "jotform",
    label: "Jotform",
    category: "business",
    hosts: ["jotform.com", "form.jotform.com"],
    intents: [
      { id: "submit", label: "Submit", matchPath: (p) => isJotformSubmitPath(p) },
      {
        id: "form",
        label: "Form",
        matchPath: (p, _params, hostname) => isJotformFormHost(hostname ?? "", p),
      },
    ],
  },
  {
    type: "zoom",
    label: "Zoom",
    category: "business",
    hosts: ["zoom.us"],
    intents: [
      {
        id: "meeting",
        label: "Meeting",
        matchPath: (p) => p.includes("/j/") || p.includes("/meeting/"),
      },
    ],
  },
  {
    type: "google-meet",
    label: "Google Meet",
    category: "business",
    hosts: ["meet.google.com"],
    intents: [{ id: "meeting", label: "Meeting" }],
  },
  {
    type: "microsoft-teams",
    label: "Microsoft Teams",
    category: "business",
    hosts: ["teams.microsoft.com", "teams.live.com"],
    intents: [{ id: "meeting", label: "Meeting" }],
  },
];
