import {
  isBlueskyProfilePath,
  isFacebookProfilePath,
  isMastodonPostPath,
  isMastodonProfilePath,
  isPinterestProfilePath,
  isRedditCommentPath,
  isRedditPostPath,
  isThreadsProfilePath,
  isTikTokLivePath,
  isTikTokProfilePath,
  isTikTokVideoPath,
  isTumblrBlogPath,
  segments,
} from "@/features/qr/content/platform-path-matching"
import {
  profileIntent,
  urlIntent,
  type PlatformDef,
} from "@/features/qr/content/intents/shared"

export const SOCIAL_PLATFORM_DEFS: readonly PlatformDef[] = [
  {
    type: "instagram",
    label: "Instagram",
    description: "Profile, post, reel, story, or highlight link.",
    collection: "social",
    category: "social",
    hosts: ["instagram.com"],
    brandIconId: "instagram",
    intents: [
      profileIntent((pathname) => {
        const segments = pathname.split("/").filter(Boolean)
        return segments.length <= 1
      }),
      urlIntent("post", "Post", (p) => p.includes("/p/")),
      urlIntent("reel", "Reel", (p) => p.includes("/reel/")),
      urlIntent("story", "Story", (p) => p.includes("/stories/") && !p.includes("/highlights/")),
      urlIntent("highlight", "Highlight", (p) => p.includes("/stories/highlights/")),
    ],
  },
  {
    type: "x",
    label: "X",
    description: "Profile, post, list, community, or space.",
    collection: "social",
    category: "social",
    hosts: ["x.com", "twitter.com"],
    brandIconId: "x",
    intents: [
      profileIntent((pathname) => {
        const segments = pathname.split("/").filter(Boolean)
        return segments.length <= 1 && !pathname.includes("/status/")
      }),
      urlIntent("status", "Post", (p) => p.includes("/status/")),
      urlIntent("list", "List", (p) => p.includes("/i/lists/")),
      urlIntent("community", "Community", (p) => p.includes("/i/communities/")),
      urlIntent("space", "Space", (p) => p.includes("/i/spaces/")),
    ],
  },
  {
    type: "tiktok",
    label: "TikTok",
    description: "Profile, video, or live link.",
    collection: "social",
    category: "social",
    hosts: ["tiktok.com", "vm.tiktok.com", "vt.tiktok.com"],
    brandIconId: "tiktok",
    intents: [
      urlIntent("video", "Video", (p) => isTikTokVideoPath(p)),
      urlIntent("live", "Live", (p) => isTikTokLivePath(p)),
      urlIntent("profile", "Profile", (p) => isTikTokProfilePath(p)),
    ],
  },
  {
    type: "youtube",
    label: "YouTube",
    description: "Channel, video, Shorts, playlist, or live.",
    collection: "social",
    category: "social",
    hosts: ["youtube.com", "youtu.be", "m.youtube.com"],
    brandIconId: "youtube",
    intents: [
      urlIntent("channel", "Channel", (p) =>
        p.startsWith("/@") || p.startsWith("/channel/") || p.startsWith("/c/"),
      ),
      urlIntent("video", "Video", (p) => p.includes("/watch") || p.startsWith("/shorts/") === false && p.includes("/v/")),
      urlIntent("shorts", "Shorts", (p) => p.includes("/shorts/")),
      urlIntent("playlist", "Playlist", (p) => p.includes("/playlist")),
      urlIntent("live", "Live", (p) => p.includes("/live")),
    ],
  },
  {
    type: "facebook",
    label: "Facebook",
    description: "Profile, page, post, group, event, or reel.",
    collection: "social",
    category: "social",
    hosts: ["facebook.com", "fb.com", "m.facebook.com"],
    brandIconId: "facebook",
    intents: [
      urlIntent("page", "Page", (p) => p.includes("/pages/") || p.includes("/profile.php")),
      urlIntent("post", "Post", (p) => p.includes("/posts/") || p.includes("/permalink/") || p.includes("story.php")),
      urlIntent("group", "Group", (p) => p.includes("/groups/")),
      urlIntent("event", "Event", (p) => p.includes("/events/")),
      urlIntent("reel", "Reel", (p) => p.includes("/reel/")),
      urlIntent("profile", "Profile", (p) => isFacebookProfilePath(p)),
    ],
  },
  {
    type: "linkedin",
    label: "LinkedIn",
    description: "Profile, company, post, or job.",
    collection: "social",
    category: "social",
    hosts: ["linkedin.com"],
    intents: [
      urlIntent("profile", "Profile", (p) => p.includes("/in/")),
      urlIntent("company", "Company", (p) => p.includes("/company/")),
      urlIntent("post", "Post", (p) => p.includes("/feed/update/") || p.includes("/posts/")),
      urlIntent("job", "Job", (p) => p.includes("/jobs/")),
    ],
  },
  {
    type: "threads",
    label: "Threads",
    description: "Profile or post link.",
    collection: "social",
    category: "social",
    hosts: ["threads.net"],
    brandIconId: "threads",
    intents: [
      urlIntent("post", "Post", (p) => p.includes("/post/")),
      urlIntent("profile", "Profile", (p) => isThreadsProfilePath(p)),
    ],
  },
  {
    type: "snapchat",
    label: "Snapchat",
    description: "Add friend, Spotlight, or Lens.",
    collection: "social",
    category: "social",
    hosts: ["snapchat.com"],
    brandIconId: "snapchat",
    intents: [
      urlIntent("add", "Add", (p) => p.includes("/add/")),
      urlIntent("spotlight", "Spotlight", (p) => p.includes("/spotlight/")),
      urlIntent("lens", "Lens", (p) => p.includes("/lens/")),
    ],
  },
  {
    type: "pinterest",
    label: "Pinterest",
    description: "Profile, pin, or board.",
    collection: "social",
    category: "social",
    hosts: ["pinterest.com"],
    brandIconId: "pinterest",
    intents: [
      urlIntent("pin", "Pin", (p) => p.includes("/pin/")),
      urlIntent("board", "Board", (p) => p.includes("/board/") || (segments(p).length >= 2 && !p.includes("/pin/"))),
      urlIntent("profile", "Profile", (p) => isPinterestProfilePath(p)),
    ],
  },
  {
    type: "reddit",
    label: "Reddit",
    description: "User, subreddit, post, or comment.",
    collection: "social",
    category: "social",
    hosts: ["reddit.com", "old.reddit.com"],
    intents: [
      urlIntent("user", "User", (p) => p.startsWith("/u/") || p.startsWith("/user/")),
      urlIntent("subreddit", "Subreddit", (p) => p.startsWith("/r/") && !p.includes("/comments/")),
      urlIntent("comment", "Comment", (p) => isRedditCommentPath(p)),
      urlIntent("post", "Post", (p) => isRedditPostPath(p)),
    ],
  },
  {
    type: "twitch",
    label: "Twitch",
    description: "Channel, video, or clip.",
    collection: "social",
    category: "social",
    hosts: ["twitch.tv", "clips.twitch.tv"],
    intents: [
      urlIntent("video", "Video", (p) => p.includes("/videos/")),
      urlIntent("clip", "Clip", (p) => p.includes("/clip/")),
      urlIntent("channel", "Channel", (p) => segments(p).length === 1),
    ],
  },
  {
    type: "bluesky",
    label: "Bluesky",
    description: "Profile or post.",
    collection: "social",
    category: "social",
    hosts: ["bsky.app"],
    intents: [
      urlIntent("post", "Post", (p) => p.includes("/post/")),
      urlIntent("profile", "Profile", (p) => isBlueskyProfilePath(p)),
    ],
  },
  {
    type: "mastodon",
    label: "Mastodon",
    description: "Profile or post on any instance.",
    collection: "social",
    category: "social",
    hosts: [],
    intents: [
      urlIntent("post", "Post", (p) => isMastodonPostPath(p)),
      urlIntent("profile", "Profile", (p) => isMastodonProfilePath(p)),
    ],
  },
  {
    type: "tumblr",
    label: "Tumblr",
    description: "Blog or post.",
    collection: "social",
    category: "social",
    hosts: ["tumblr.com"],
    intents: [
      urlIntent("post", "Post", (p) => p.includes("/post/")),
      urlIntent("blog", "Blog", (p) => isTumblrBlogPath(p)),
    ],
  },
]
