export type RaycastWallpaper = {
  id: string;
  label: string;
  path: string;
  previewPath: string;
  source: "raycast";
};

export const RAYCAST_WALLPAPERS: readonly RaycastWallpaper[] = [
  {
    id: "glaze-1",
    label: "Glaze 1",
    path: "/backgrounds/raycast/glaze-1.webp",
    previewPath: "/backgrounds/raycast/glaze-1-preview.webp",
    source: "raycast",
  },
  {
    id: "glaze-2",
    label: "Glaze 2",
    path: "/backgrounds/raycast/glaze-2.webp",
    previewPath: "/backgrounds/raycast/glaze-2-preview.webp",
    source: "raycast",
  },
  {
    id: "red-distortion-1",
    label: "Red Distortion 1",
    path: "/backgrounds/raycast/red-distortion-1.webp",
    previewPath: "/backgrounds/raycast/red-distortion-1-preview.webp",
    source: "raycast",
  },
  {
    id: "red-distortion-2",
    label: "Red Distortion 2",
    path: "/backgrounds/raycast/red-distortion-2.webp",
    previewPath: "/backgrounds/raycast/red-distortion-2-preview.webp",
    source: "raycast",
  },
  {
    id: "red-distortion-3",
    label: "Red Distortion 3",
    path: "/backgrounds/raycast/red-distortion-3.webp",
    previewPath: "/backgrounds/raycast/red-distortion-3-preview.webp",
    source: "raycast",
  },
  {
    id: "red-distortion-4",
    label: "Red Distortion 4",
    path: "/backgrounds/raycast/red-distortion-4.webp",
    previewPath: "/backgrounds/raycast/red-distortion-4-preview.webp",
    source: "raycast",
  },
  {
    id: "blue-distortion-1",
    label: "Blue Distortion 1",
    path: "/backgrounds/raycast/blue-distortion-1.webp",
    previewPath: "/backgrounds/raycast/blue-distortion-1-preview.webp",
    source: "raycast",
  },
  {
    id: "blue-distortion-2",
    label: "Blue Distortion 2",
    path: "/backgrounds/raycast/blue-distortion-2.webp",
    previewPath: "/backgrounds/raycast/blue-distortion-2-preview.webp",
    source: "raycast",
  },
  {
    id: "mono-dark-distortion-1",
    label: "Mono Dark Distortion 1",
    path: "/backgrounds/raycast/mono-dark-distortion-1.webp",
    previewPath: "/backgrounds/raycast/mono-dark-distortion-1-preview.webp",
    source: "raycast",
  },
  {
    id: "mono-dark-distortion-2",
    label: "Mono Dark Distortion 2",
    path: "/backgrounds/raycast/mono-dark-distortion-2.webp",
    previewPath: "/backgrounds/raycast/mono-dark-distortion-2-preview.webp",
    source: "raycast",
  },
  {
    id: "mono-light-distortion-1",
    label: "Mono Light Distortion 1",
    path: "/backgrounds/raycast/mono-light-distortion-1.webp",
    previewPath: "/backgrounds/raycast/mono-light-distortion-1-preview.webp",
    source: "raycast",
  },
  {
    id: "mono-light-distortion-2",
    label: "Mono Light Distortion 2",
    path: "/backgrounds/raycast/mono-light-distortion-2.webp",
    previewPath: "/backgrounds/raycast/mono-light-distortion-2-preview.webp",
    source: "raycast",
  },
  {
    id: "chromatic-dark-1",
    label: "Chromatic Dark 1",
    path: "/backgrounds/raycast/chromatic-dark-1.webp",
    previewPath: "/backgrounds/raycast/chromatic-dark-1-preview.webp",
    source: "raycast",
  },
  {
    id: "chromatic-dark-2",
    label: "Chromatic Dark 2",
    path: "/backgrounds/raycast/chromatic-dark-2.webp",
    previewPath: "/backgrounds/raycast/chromatic-dark-2-preview.webp",
    source: "raycast",
  },
  {
    id: "chromatic-light-1",
    label: "Chromatic Light 1",
    path: "/backgrounds/raycast/chromatic-light-1.webp",
    previewPath: "/backgrounds/raycast/chromatic-light-1-preview.webp",
    source: "raycast",
  },
  {
    id: "chromatic-light-2",
    label: "Chromatic Light 2",
    path: "/backgrounds/raycast/chromatic-light-2.webp",
    previewPath: "/backgrounds/raycast/chromatic-light-2-preview.webp",
    source: "raycast",
  },
  {
    id: "cube",
    label: "Cube",
    path: "/backgrounds/raycast/cube.webp",
    previewPath: "/backgrounds/raycast/cube-preview.webp",
    source: "raycast",
  },
  {
    id: "cube-mono",
    label: "Cube Mono",
    path: "/backgrounds/raycast/cube-mono.webp",
    previewPath: "/backgrounds/raycast/cube-mono-preview.webp",
    source: "raycast",
  },
  {
    id: "loupe",
    label: "Loupe",
    path: "/backgrounds/raycast/loupe.webp",
    previewPath: "/backgrounds/raycast/loupe-preview.webp",
    source: "raycast",
  },
  {
    id: "loupe-mono-dark",
    label: "Loupe Mono Dark",
    path: "/backgrounds/raycast/loupe-mono-dark.webp",
    previewPath: "/backgrounds/raycast/loupe-mono-dark-preview.webp",
    source: "raycast",
  },
  {
    id: "loupe-mono-light",
    label: "Loupe Mono Light",
    path: "/backgrounds/raycast/loupe-mono-light.webp",
    previewPath: "/backgrounds/raycast/loupe-mono-light-preview.webp",
    source: "raycast",
  },
  {
    id: "blob",
    label: "Blob",
    path: "/backgrounds/raycast/blob.webp",
    previewPath: "/backgrounds/raycast/blob-preview.webp",
    source: "raycast",
  },
  {
    id: "blob-red",
    label: "Blob Red",
    path: "/backgrounds/raycast/blob-red.webp",
    previewPath: "/backgrounds/raycast/blob-red-preview.webp",
    source: "raycast",
  },
  {
    id: "raycast-logo",
    label: "Raycast Logo",
    path: "/backgrounds/raycast/raycast-logo.webp",
    previewPath: "/backgrounds/raycast/raycast-logo-preview.webp",
    source: "raycast",
  },
  {
    id: "autumnal-peach",
    label: "Autumnal Peach",
    path: "/backgrounds/raycast/autumnal-peach.webp",
    previewPath: "/backgrounds/raycast/autumnal-peach-preview.webp",
    source: "raycast",
  },
  {
    id: "blossom",
    label: "Blossom",
    path: "/backgrounds/raycast/blossom.webp",
    previewPath: "/backgrounds/raycast/blossom-preview.webp",
    source: "raycast",
  },
  {
    id: "blushing-fire",
    label: "Blushing Fire",
    path: "/backgrounds/raycast/blushing-fire.webp",
    previewPath: "/backgrounds/raycast/blushing-fire-preview.webp",
    source: "raycast",
  },
  {
    id: "bright-rain",
    label: "Bright Rain",
    path: "/backgrounds/raycast/bright-rain.webp",
    previewPath: "/backgrounds/raycast/bright-rain-preview.webp",
    source: "raycast",
  },
  {
    id: "floss",
    label: "Floss",
    path: "/backgrounds/raycast/floss.webp",
    previewPath: "/backgrounds/raycast/floss-preview.webp",
    source: "raycast",
  },
  {
    id: "glass-rainbow",
    label: "Glass Rainbow",
    path: "/backgrounds/raycast/glass-rainbow.webp",
    previewPath: "/backgrounds/raycast/glass-rainbow-preview.webp",
    source: "raycast",
  },
  {
    id: "good-vibes",
    label: "Good Vibes",
    path: "/backgrounds/raycast/good-vibes.webp",
    previewPath: "/backgrounds/raycast/good-vibes-preview.webp",
    source: "raycast",
  },
  {
    id: "moonrise",
    label: "Moonrise",
    path: "/backgrounds/raycast/moonrise.webp",
    previewPath: "/backgrounds/raycast/moonrise-preview.webp",
    source: "raycast",
  },
  {
    id: "ray-of-lights",
    label: "Ray of Lights",
    path: "/backgrounds/raycast/ray-of-lights.webp",
    previewPath: "/backgrounds/raycast/ray-of-lights-preview.webp",
    source: "raycast",
  },
  {
    id: "rose-thorn",
    label: "Rose Thorn",
    path: "/backgrounds/raycast/rose-thorn.webp",
    previewPath: "/backgrounds/raycast/rose-thorn-preview.webp",
    source: "raycast",
  },
] as const;

function getRaycastWallpaper(id: string): RaycastWallpaper | undefined {
  return RAYCAST_WALLPAPERS.find((wallpaper) => wallpaper.id === id);
}
